services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wolt_flask
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: company    
    ports:
      - 80:80
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    container_name: wolt_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: company
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wolt_phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8080:80

  arangodb:
    image: arangodb:latest
    container_name: wolt_arangodb
    environment:
      ARANGO_ROOT_PASSWORD: password
    volumes:
      - arangodb_data:/var/lib/arangodb3
    ports:
      - 8529:8529


  redis:
    image: redis:latest
    container_name: wolt_redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  arangodb_data:
  redis_data:


